sonar.projectKey=bcgov_cisb-referral
sonar.organization=bcgov
sonar.projectName=cisb-referral

# Path to sources
sonar.sources=admin-app/src,referral-app/src,backend/src

# Source encoding
sonar.sourceEncoding=UTF-8
