apiVersion: v1
kind: ConfigMap
metadata:
  name: cisb-referral-admin-app-config
  labels:
    app.kubernetes.io/name: cisb-referral-admin-app
data:
  config.js: |
    window.__APP_CONFIG__ = {
      KC_URL: {{ .Values.config.KC_URL | quote }},
      KC_REALM: {{ .Values.config.KC_REALM | quote }},
      KC_CLIENT_ID: {{ .Values.config.KC_CLIENT_ID | quote }},
    };
